---
version: '2'
services:
  db:
    image: tutum/influxdb 
    ports:
      - "8083:8083"
      - "8086:8086"
    environment:
      - ADMIN_USER=root
      - INFLUXDB_INIT_PWD=pedrocesar
      - PRE_CREATE_DB=speedtest
  web:
    image: tutum/grafana 
    links:
      - db:db
    ports:
      - "8080:80"
    environment:
      - HTTP_USER=admin
      - HTTP_PASS=pedrocesar
      - INFLUXDB_PROTO=http
      - INFLUXDB_HOST=db
      - INFLUXDB_PORT=8086
      - INFLUXDB_NAME=speedtest
      - INFLUXDB_USER=root
      - INFLUXDB_PASS=pedrocesar
  testing:
    image: pedrocesarti/internet-speedtest-docker
    links:
      - db:db
    environment:
      - TIME_SLEEP=10
