---
version: '2'
services:
  db:
    image: tutum/influxdb 
    ports:
      - "8083:8083"
      - "8086:8086"
    environment:
      - ADMIN_USER=${INFLUX_USER}
      - INFLUXDB_INIT_PWD=${INFLUX_PASSWD}
    env_file:
      - ./env/db.env
  testing:
    image: pedrocesarti/internet-speedtest-docker:speedtest
    links:
      - db:db
    environment:
      - TEST_INTERVAL=${TEST_INTERVAL}
    env_file:
      - ./env/testing.env
